//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badger2018.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TempsDemieJournee {
            get {
                return ((global::System.TimeSpan)(this["TempsDemieJournee"]));
            }
            set {
                this["TempsDemieJournee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TempsMinPause {
            get {
                return ((global::System.TimeSpan)(this["TempsMinPause"]));
            }
            set {
                this["TempsMinPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan PlageFixeMatinStart {
            get {
                return ((global::System.TimeSpan)(this["PlageFixeMatinStart"]));
            }
            set {
                this["PlageFixeMatinStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan PlageFixeMatinFin {
            get {
                return ((global::System.TimeSpan)(this["PlageFixeMatinFin"]));
            }
            set {
                this["PlageFixeMatinFin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan PlageFixeApremStart {
            get {
                return ((global::System.TimeSpan)(this["PlageFixeApremStart"]));
            }
            set {
                this["PlageFixeApremStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan PlageFixeApremFin {
            get {
                return ((global::System.TimeSpan)(this["PlageFixeApremFin"]));
            }
            set {
                this["PlageFixeApremFin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string First {
            get {
                return ((string)(this["First"]));
            }
            set {
                this["First"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ModeBadgement {
            get {
                return ((int)(this["ModeBadgement"]));
            }
            set {
                this["ModeBadgement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemptBlockShutdown {
            get {
                return ((bool)(this["TemptBlockShutdown"]));
            }
            set {
                this["TemptBlockShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uri {
            get {
                return ((string)(this["Uri"]));
            }
            set {
                this["Uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UriParam {
            get {
                return ((string)(this["UriParam"]));
            }
            set {
                this["UriParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FfExePath {
            get {
                return ((string)(this["FfExePath"]));
            }
            set {
                this["FfExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrowserIndex {
            get {
                return ((int)(this["BrowserIndex"]));
            }
            set {
                this["BrowserIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoBadgeAtStart {
            get {
                return ((bool)(this["IsAutoBadgeAtStart"]));
            }
            set {
                this["IsAutoBadgeAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ActionButtonClose {
            get {
                return ((int)(this["ActionButtonClose"]));
            }
            set {
                this["ActionButtonClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotifEndPfMatin {
            get {
                return ((bool)(this["ShowNotifEndPfMatin"]));
            }
            set {
                this["ShowNotifEndPfMatin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotifEndPfAprem {
            get {
                return ((bool)(this["ShowNotifEndPfAprem"]));
            }
            set {
                this["ShowNotifEndPfAprem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotifEndPause {
            get {
                return ((bool)(this["ShowNotifEndPause"]));
            }
            set {
                this["ShowNotifEndPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotifEndTheo {
            get {
                return ((bool)(this["ShowNotifEndTheo"]));
            }
            set {
                this["ShowNotifEndTheo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNotif1Enabled {
            get {
                return ((bool)(this["IsNotif1Enabled"]));
            }
            set {
                this["IsNotif1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNotif2Enabled {
            get {
                return ((bool)(this["IsNotif2Enabled"]));
            }
            set {
                this["IsNotif2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Notif1Time {
            get {
                return ((global::System.TimeSpan)(this["Notif1Time"]));
            }
            set {
                this["Notif1Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Notif2Time {
            get {
                return ((global::System.TimeSpan)(this["Notif2Time"]));
            }
            set {
                this["Notif2Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Notif1Text {
            get {
                return ((string)(this["Notif1Text"]));
            }
            set {
                this["Notif1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Notif2Text {
            get {
                return ((string)(this["Notif2Text"]));
            }
            set {
                this["Notif2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsConsentUse {
            get {
                return ((bool)(this["IsConsentUse"]));
            }
            set {
                this["IsConsentUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoBadgeMeridienne {
            get {
                return ((bool)(this["IsAutoBadgeMeridienne"]));
            }
            set {
                this["IsAutoBadgeMeridienne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLastBadgeIsAutoShutdown {
            get {
                return ((bool)(this["IsLastBadgeIsAutoShutdown"]));
            }
            set {
                this["IsLastBadgeIsAutoShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastBadgeDelay {
            get {
                return ((int)(this["LastBadgeDelay"]));
            }
            set {
                this["LastBadgeDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBtnManuelBadgeIsWithHotKeys {
            get {
                return ((bool)(this["IsBtnManuelBadgeIsWithHotKeys"]));
            }
            set {
                this["IsBtnManuelBadgeIsWithHotKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:30:00")]
        public global::System.TimeSpan TempsMaxJournee {
            get {
                return ((global::System.TimeSpan)(this["TempsMaxJournee"]));
            }
            set {
                this["TempsMaxJournee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeltaAutoBadgeageMinute {
            get {
                return ((int)(this["DeltaAutoBadgeageMinute"]));
            }
            set {
                this["DeltaAutoBadgeageMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gv_detailBadgeage")]
        public string UriVerif {
            get {
                return ((string)(this["UriVerif"]));
            }
            set {
                this["UriVerif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseAlternateNotification {
            get {
                return ((bool)(this["IsUseAlternateNotification"]));
            }
            set {
                this["IsUseAlternateNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07:00:00")]
        public global::System.TimeSpan HeureMinJournee {
            get {
                return ((global::System.TimeSpan)(this["HeureMinJournee"]));
            }
            set {
                this["HeureMinJournee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsStopCptAtMax {
            get {
                return ((bool)(this["IsStopCptAtMax"]));
            }
            set {
                this["IsStopCptAtMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAdd5minCpt {
            get {
                return ((bool)(this["IsAdd5minCpt"]));
            }
            set {
                this["IsAdd5minCpt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDailyDisableAutoBadgeMerid {
            get {
                return ((bool)(this["IsDailyDisableAutoBadgeMerid"]));
            }
            set {
                this["IsDailyDisableAutoBadgeMerid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotifWhenSessUnlockAfterMidi {
            get {
                return ((bool)(this["ShowNotifWhenSessUnlockAfterMidi"]));
            }
            set {
                this["ShowNotifWhenSessUnlockAfterMidi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05:30:00")]
        public global::System.TimeSpan TempsMaxDemieJournee {
            get {
                return ((global::System.TimeSpan)(this["TempsMaxDemieJournee"]));
            }
            set {
                this["TempsMaxDemieJournee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseGeckoDebug {
            get {
                return ((bool)(this["IsUseGeckoDebug"]));
            }
            set {
                this["IsUseGeckoDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zvpw068.r12.an.cnav:7796/Pages/Espace%20RH/Mon%20Suivi%20RH/GTA/GTA_MesBag" +
            "eages.aspx?Rubrique=ERHMSRHMB")]
        public string UrlMesPointages {
            get {
                return ((string)(this["UrlMesPointages"]));
            }
            set {
                this["UrlMesPointages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sirhius-r12.n06.an.cnav/hra-space/portal")]
        public string UrlSirhius {
            get {
                return ((string)(this["UrlSirhius"]));
            }
            set {
                this["UrlSirhius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zvpw068.r12.an.cnav:7796/Pages/Espace%20RH/Mon%20Suivi%20RH/GTA/GTA_TpsRee" +
            "l.aspx?Rubrique=ERHMSRHCT")]
        public string UrlCptTpsReel {
            get {
                return ((string)(this["UrlCptTpsReel"]));
            }
            set {
                this["UrlCptTpsReel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGlobalShowNotifications {
            get {
                return ((bool)(this["IsGlobalShowNotifications"]));
            }
            set {
                this["IsGlobalShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPlaySoundAtLockMidi {
            get {
                return ((bool)(this["IsPlaySoundAtLockMidi"]));
            }
            set {
                this["IsPlaySoundAtLockMidi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int SoundPlayedAtLockMidi {
            get {
                return ((int)(this["SoundPlayedAtLockMidi"]));
            }
            set {
                this["SoundPlayedAtLockMidi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CSharp\\Données accessoires\\Badger\\update.xml")]
        public string UpdateXmlUri {
            get {
                return ((string)(this["UpdateXmlUri"]));
            }
            set {
                this["UpdateXmlUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoundDeviceFullName {
            get {
                return ((string)(this["SoundDeviceFullName"]));
            }
            set {
                this["SoundDeviceFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TipsLastInt {
            get {
                return ((int)(this["TipsLastInt"]));
            }
            set {
                this["TipsLastInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTipsAtStart {
            get {
                return ((bool)(this["ShowTipsAtStart"]));
            }
            set {
                this["ShowTipsAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int SoundPlayedAtLockMidiVolume {
            get {
                return ((int)(this["SoundPlayedAtLockMidiVolume"]));
            }
            set {
                this["SoundPlayedAtLockMidiVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsStopCptAtMaxDemieJournee {
            get {
                return ((bool)(this["IsStopCptAtMaxDemieJournee"]));
            }
            set {
                this["IsStopCptAtMaxDemieJournee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TypeBadgeageBtnM {
            get {
                return ((int)(this["TypeBadgeageBtnM"]));
            }
            set {
                this["TypeBadgeageBtnM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRemoveLegacyShorcutFirefox {
            get {
                return ((bool)(this["IsRemoveLegacyShorcutFirefox"]));
            }
            set {
                this["IsRemoveLegacyShorcutFirefox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z017695")]
        public string licencedUser {
            get {
                return ((string)(this["licencedUser"]));
            }
            set {
                this["licencedUser"] = value;
            }
        }
    }
}
