// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;


[assembly: AssemblyVersion("1.3.0901.1510")]
[assembly: AssemblyFileVersion("1.3.0901.1510")]

