BEGIN TRANSACTION;
DROP TABLE IF EXISTS `TYBADGEAGES`;
CREATE TABLE IF NOT EXISTS `TYBADGEAGES` (
	`TYPE_BADGE`	INTEGER,
	`BADGE_NAME`	TEXT,
	PRIMARY KEY(`TYPE_BADGE`)
);
INSERT INTO `TYBADGEAGES` VALUES (1,'PLAGE_TRAV_MATIN_START');
INSERT INTO `TYBADGEAGES` VALUES (2,'PLAGE_TRAV_MATIN_END');
INSERT INTO `TYBADGEAGES` VALUES (3,'PLAGE_TRAV_APREM_START');
INSERT INTO `TYBADGEAGES` VALUES (4,'PLAGE_TRAV_APREM_END');
INSERT INTO `TYBADGEAGES` VALUES (10,'PAUSE_START');
INSERT INTO `TYBADGEAGES` VALUES (11,'PAUSE_END');
DROP TABLE IF EXISTS `JOURS`;
CREATE TABLE IF NOT EXISTS `JOURS` (
	`DATE_JOUR`	TEXT,
	`TYPE_JOUR`	INTEGER DEFAULT 0,
	`IS_COMPLETE`	INTEGER DEFAULT 0,
	`ETAT_BADGER`	INTEGER,
	`OLD_ETAT_BADGER`	INTEGER,
	`TPS_TRAV_SECONDE`	INTEGER,
	`NB_BADGEAGE`	INTEGER
);

DROP TABLE IF EXISTS `BADGEAGES`;
CREATE TABLE IF NOT EXISTS `BADGEAGES` (
	`DATE_BADGE`	TEXT,
	`TYPE_BADGE`	INTEGER,
	`RELATION_KEY`	TEXT,
	`TIME_BADGE`	TEXT,
	`DT_ADDED`	TEXT,
	`CD_AT_TIME`	TEXT,
	PRIMARY KEY(`DATE_BADGE`,`TYPE_BADGE`,`RELATION_KEY`)
);

DROP VIEW IF EXISTS `BADGEAGES_TYPE`;
CREATE VIEW BADGEAGES_TYPE AS Select b.DATE_BADGE,  b.TIME_BADGE, t.BADGE_NAME, b.TYPE_BADGE AS BADGE_INT FROM BADGEAGES b, TYBADGEAGES t WHERE b.TYPE_BADGE = t.TYPE_BADGE;
COMMIT;
