BEGIN TRANSACTION;
DROP TABLE IF EXISTS `BADGEAGES`;
CREATE TABLE IF NOT EXISTS `BADGEAGES` (
	`DATEBADGE`	TEXT,
	`TYPEBADGE`	INTEGER,
	`TIMEBADGE`	TEXT,
	PRIMARY KEY(`DATEBADGE`,`TYPEBADGE`)
);
COMMIT;
